#!/bin/bash

run_test()
{
    SCRIPT=$1
    SUBMISSION_REPO_NAME=$2
    TEST_SOURCE_REPO_NAME=$3

    export PATH_TO_SUBMISSION_REPO=$PWD/$SUBMISSION_REPO_NAME
    export PATH_TO_TEST_SOURCE_REPO=$PWD/$TEST_SOURCE_REPO_NAME

    chmod 755 $SCRIPT
    bash -$OPTIONS $SCRIPT
}
